### ISSUE TITLE
Preserve faces normal even with flipped components

### ISSUE THREAD

**Issue by thomthom** [SketchUp/sketchup-stl#129]
![flippednormals](https://f.cloud.github.com/assets/192418/2308487/022eb35c-a2bf-11e3-8f3e-767967f05296.png)

When exporting a model which has mirrored components the facets of the mirrored geometry has its vertices defined in the wrong direction. We should detect when a component is mirrored and reverse the order of the vertices we add.

**Comment by jimfoltz** [comment]
Close?
