### ISSUE TITLE
Incorrect Link on EW Page

### ISSUE THREAD

**Issue by jimfoltz** [SketchUp/sketchup-stl#151]
This link on the [EW page](https://extensions.sketchup.com/en/content/sketchup-stl) is incorrect.

![2015-02_230](https://cloud.githubusercontent.com/assets/137514/6096636/9a6075f8-af6a-11e4-9c75-c0c3fa6e4506.png)

**Comment by thomthom** [comment]
Fixed! Thanks for reporting.
