### ISSUE TITLE
Export STL raises exception in Ruby Console

### ISSUE THREAD

**Issue by grit96** [SketchUp/sketchup-stl#152]
Using SketchUp 6 under Wine.

I cannot get the export STL function to work, it shows this error in the console.
Import from STL works fine.

```
Error: #<TypeError: cannot convert Hash into String>
C:/Program Files (x86)/Google/Google SketchUp 6/Plugins/sketchup-stl/SKUI/window.rb:403:in `initialize'
C:/Program Files (x86)/Google/Google SketchUp 6/Plugins/sketchup-stl/SKUI/window.rb:403:in `new'
C:/Program Files (x86)/Google/Google SketchUp 6/Plugins/sketchup-stl/SKUI/window.rb:403:in `init_webdialog'
C:/Program Files (x86)/Google/Google SketchUp 6/Plugins/sketchup-stl/SKUI/window.rb:193:in `show'
C:/Program Files (x86)/Google/Google SketchUp 6/Plugins/sketchup-stl/exporter.rb:312:in `do_options'
C:/Program Files (x86)/Google/Google SketchUp 6/Plugins/sketchup-stl/exporter.rb:326
C:/Program Files (x86)/Google/Google SketchUp 6/Plugins/sketchup-stl/exporter.rb:325:in `call'
```

**Comment by Aerilius** [comment]
Me neither if when I dig out SketchUp 6. It seems the **Hash** argument for `UI::WebDialog.new` has been implemented in SketchUp 7 or 7.1 ([documentation](http://www.sketchup.com/intl/en/developer/docs/ourdoc/webdialog#new) misses that, a case for [SketchUp-Ruby-API-Doc](https://github.com/jimfoltz/SketchUp-Ruby-API-Doc/)).

And I wouldn't expect SketchUp or anybody to support that old versions, even I have it hard to support SU8, some tend to go 2014/2015 only. By the way, if you install *latest* Wine 1.7.x, you can also use Ruby 2.0 and SU2015 and SU2014.

**Comment by grit96** [comment]
I can run 2013 with the latest wine version but with 2015 I get these errors:
```
err:module:import_dll Library mfc100u.dll (which is needed by L"Z:\\home\\geraint\\.wine\\drive_c\\Program Files (x86)\\SketchUp\\SketchUp 2015\\SketchUp.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"Z:\\home\\geraint\\.wine\\drive_c\\Program Files (x86)\\SketchUp\\SketchUp 2015\\SketchUp.exe" failed, status c0000135
```

**Comment by grit96** [comment]
Not supporting SketchUp versions below SketchUp 8
