### ISSUE TITLE
File:"sketchup-stl.rb" refers to MIT License in file header

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/sketchup-stl#155]
ALL Ruby files refer to MIT License in file header.

Extension `copyright` attribute ("**sketchup-stl.rb**") states plugin is released under **Apache 2.0 License**.

HTML, CSS, and Js files have no copyright or license information.

**Comment by thomthom** [comment]
Good catch. I thought all of this has been replaced already. Doing a full search now.
