### ISSUE TITLE
Can we get this signed for 2017?

### ISSUE THREAD

**Issue by jimfoltz** [SketchUp/sketchup-stl#161]
Thanks.

**Comment by elfhelmp** [comment]
I subscribe. Also import doesn't work, I can only see export option. Big thanks to all devs making our lives easier so far!

**Comment by thomthom** [comment]
@jimfoltz - we'll look into that. Ideally we want to bulk-sign extensions, but maybe we we should get the most popular from the SketchUp account updated manually.

**Comment by thomthom** [comment]
Should be signed now.
