### ISSUE TITLE
Binary preview is solid black in macOS (but ASCII is ok)

### ISSUE THREAD

**Issue by jsejcksn** [SketchUp/sketchup-stl#163]
Here are some screenshots from the file preview pane:

![ASCII](https://cloud.githubusercontent.com/assets/868251/21284464/57b517b2-c3e1-11e6-8674-710752ce3198.png)

![Binary](https://cloud.githubusercontent.com/assets/868251/21284466/611e7514-c3e1-11e6-9395-29397836493d.png)

**Comment by thomthom** [comment]
The STL file only carry information about triangles. No materials or shading. I can't think of anything the exporter can do. This seem to be to be a Quick View issue.

(btw, attaching sample STL files would help when reporting issues.)

**Comment by thomthom** [comment]
Do this happen to binary STL files from SU only? Did you compare against binary files from other sources? (If so can you provide example files of what work and what doesn't?)

**Comment by jsejcksn** [comment]
Hi @thomthom:

I have attached the relevant files (the same ones in #162). I only have Fusion 360 and SketchUp installed.

[stl-f-export-test.zip](https://github.com/SketchUp/sketchup-stl/files/659694/stl-f-export-test.zip)

**Comment by jimfoltz** [comment]
I wonder if the preview app is looking for a color in the "unused" bytes of the binary stl format?

**Comment by jimfoltz** [comment]
See issue #25 about color in stl files.

**Comment by thomthom** [comment]
The unused bytes are just reserved. the specs doesn't specify any color data. In any case, that `uint16` "attribute-size` is written as 0 in the SketchUp exporter. Like all other exporters I've seen.

I'm downloading the STL now and will inspect it. This was one from SU, right? Have you seen an binary STL that didn't display as black?

Btw, what version of OSX are you using?

**Comment by thomthom** [comment]
I see now - the ZIP had examples from SU and Fusion. And the Fusion binary files doesn't display as black?

**Comment by jsejcksn** [comment]
The STLs exported from Fusion 360 display with the same style/color as the ASCII one exported from SketchUp (not solid black). I'm using macOS 10.12.2.

**Comment by jimfoltz** [comment]
The fusion binaries include a COLOR string in the header, where the SketchUp binaries do not. Maybe that's all it is.

    irb(main):056:0* File.read("f-fusion360-zup-bin.stl", 80) 
    => "STLB ATF 2.0.0.9000 COLOR=\xA0\xA0\xA0\xFF   

    irb(main):050:0* File.read("f-fusion360-yup-bin.stl", 80)
    => "STLB ATF 2.0.0.9000 COLOR=\xC2\xA0\xC2\xA0\xC2\xA0\xC3\xBF

**Comment by jimfoltz** [comment]
@jsejcksn Here is a SketchUp binary stl with a COLOR string in the header - can you try it?

[sketchup-bin-Z.zip](https://github.com/SketchUp/sketchup-stl/files/662441/sketchup-bin-Z.zip)

**Comment by jsejcksn** [comment]
Still looks the same:

![1](https://cloud.githubusercontent.com/assets/868251/21333411/1e95eed0-c615-11e6-9101-f8e686c116ce.png)
![2](https://cloud.githubusercontent.com/assets/868251/21333412/1e9d7434-c615-11e6-8e45-4c2d06b5a658.png)

**Comment by jimfoltz** [comment]
One more please? 
[Untitled.zip](https://github.com/SketchUp/sketchup-stl/files/662469/Untitled.zip)

**Comment by jimfoltz** [comment]
@jsejcksn I didn't change the orientation.

**Comment by jsejcksn** [comment]
Same
🤷‍♂️

![default](https://cloud.githubusercontent.com/assets/868251/21334542/07f7c5b4-c61e-11e6-9757-baefd94b2d0a.png)
![zoom](https://cloud.githubusercontent.com/assets/868251/21334543/07f865dc-c61e-11e6-87db-d5310c9622cf.png)

**Comment by thomthom** [comment]
Given that STL doesn't have any official color data I'm closing this as Won't Fix. The issue lies in the OS-X preview functionality.

**Comment by jsejcksn** [comment]
@jimfoltz Did you see this? https://en.wikipedia.org/wiki/STL_(file_format)#Color_in_binary_STL Maybe it has something to do with it.

**Comment by thomthom** [comment]
Hm... Using the comment section for unofficial data is one thing. But using the attribute byte count is troublesome. Those two bytes indicate the size of additional data. But they should not contain data themselves.

> After these follows a 2-byte ("short") unsigned integer that is the "attribute byte count" – in the standard format, this should be zero because most software does not understand anything else.

By the specs the STL parsers should be reading the attribute byte count and skip past it unless they know what it represent.

**Comment by jsejcksn** [comment]
Ok. I'm definitely in favor of upholding standards.

**Comment by jimfoltz** [comment]
Is the STL preview a built-in, or a plugin for Quick Look?

**Comment by jsejcksn** [comment]
Built-in

**Comment by thomthom** [comment]
Finding reports of various issues with the STL preview in OS X: http://forums.autodesk.com/t5/design-validate-document/360-stl-export-and-mac-os-quick-look-is-blank/td-p/6264439

> It appears that the STL viewer in El Capitan doesn't have full support for binary STL format.

**Comment by thomthom** [comment]
https://discussions.apple.com/thread/5593219?tstart=0
This thread indicate that third party applications can conflict.

**Comment by thomthom** [comment]
I had a look on a fairly fresh mac with 10.11.6;

![screen shot 2016-12-20 at 14 33 10](https://cloud.githubusercontent.com/assets/192418/21352360/7122322e-c6c1-11e6-8fad-dd2c1fcb7472.png)

The Fusion binary STL files didn't display at all. SketchUp binary STL files displayed as black. ASCII files worked fine.

**Comment by jimfoltz** [comment]
It would be nice to provide better support for the Mac binary preview. I unfortunately don't have one so I can't be of much help unless someone can come up with what exact format the preview app is looking for.

**Comment by thomthom** [comment]
If we got hold of an STL file in binary format that displayed correctly we could look at possible amendments to the exporter.

**Comment by jimfoltz** [comment]
@driven says[1] the "cube.stl" from here[2] looks normal in the Mac preview. It is a binary stl with nothing but spaces in the header. 

1. http://forums.sketchup.com/t/binary-stl-previews-on-mac/36184

2. http://people.sc.fsu.edu/~jburkardt/data/stlb/stlb.html

**Comment by driven** [comment]
Found a few others that have more header content, in the Meshlab Sample's download...
[Here](https://sourceforge.net/projects/meshlab/files/meshlab/MeshLab%20sample%20datasets/MeshLabSampleDataset.zip/download)
knot_max_simplified.STL and conrod.stl both display correctly...

john

**Comment by jimfoltz** [comment]
I wonder if Fusion 360 adds it's own plugin over-ride to the quick look viewer.

**Comment by driven** [comment]
AutoCad would **never** block other apps from reading it's content, would they...

john

**Comment by driven** [comment]
@jimfoltz, I converted both failing binary files using assimp, the Fusion one then displayed correctly but the SU one was still black...

so I then did a diff to see on the assimp versions and the SU > assimp has **facet normal nan nan nan** throughout,  where the fusion > assimp always shows values **facet normal 0 0 1** etc...

I think it shows that Assimp can't read any of the face normals and the I suspect 'quicklook' has the same issue...

john

**Comment by jimfoltz** [comment]
I don't remember why the normals are not being included in the binary export - maybe it just never came up.  Here is a binary stl exported from SketchUp with correct normals. How does it look?

[2016-12-21.zip](https://github.com/SketchUp/sketchup-stl/files/667692/2016-12-21.zip)

**Comment by driven** [comment]
![theticket](https://cloud.githubusercontent.com/assets/227987/21411023/226f8920-c7dd-11e6-857c-2b0662162679.gif)

that works...

**Comment by jimfoltz** [comment]
Yay. Thank you for your invaluable insight and effort.

**Comment by thomthom** [comment]
Ah! I never noticed we wrote out `0,0,0` for the normals... Nice catch!

![image](https://cloud.githubusercontent.com/assets/192418/21421261/36f4340e-c832-11e6-9563-b9b7b3dd6189.png)

Thanks for being persistent and sticking with this one.

**Comment by jimfoltz** [comment]
OT: I just googled that editor - binary templates look like an incredibly useful feature.

**Comment by thomthom** [comment]
Yup - very nice editor. The templates is worth the cost by itself. There was a binary STL template available in their repository. I made some changes to it so that it could read the special header Fushion creates (extract version info and color info).
