### ISSUE TITLE
Does not support Sketchup 8 as claimed

### ISSUE THREAD

**Issue by TDHofstetter** [SketchUp/sketchup-stl#181]
When this .RBZ script is decompressed into the underlying .RB script and left in the Plugins directory, it makes Sketchup 8 barf on startup.

This is in diametric opposition to the claim that this plugin is expected to work with SketchUp 8.

![image](https://user-images.githubusercontent.com/77169984/104855545-6295d200-58db-11eb-8a66-42d038d37ea4.png)

**Comment by thomthom** [comment]
> it makes Sketchup 8 barf on startup.

Are you getting an error message? If so, what does it say?

**Comment by TDHofstetter** [comment]
I've managed to resolve the situation. Thanks, Tom.

-- Tim --
     On Monday, January 18, 2021, 04:45:23 AM EST, Thomas Thomassen <notifications@github.com> wrote:  
 
 



it makes Sketchup 8 barf on startup.


Are you getting an error message? If so, what does it say?

**Comment by thomthom** [comment]
How did you resolve it?

**Comment by thomthom** [comment]
How did you resolve it?

**Comment by TDHofstetter** [comment]
I... failed to notice, when I unzipped the .rbz into an .rb, that the file contained a subdirectory that needed to be moved along with the .rb; lacking that subdirectory, the script triggers a hard error in SketchUp on startup.

The presence of a whole subdirectory full of support files is very unusual for a SketchUp plugin. It would have been much better if the .rbz had contained a readme.first or even a README.NOW right alongside the rb.

-- Tim --
     On Tuesday, January 19, 2021, 08:37:07 AM EST, Thomas Thomassen <notifications@github.com> wrote:  
 
 


How did you resolve it?

**Comment by thomthom** [comment]
SketchUp 8 Maintenance Release 2 and newer supports installation of `.rbz` files via `Preferences > Extensions`.

**Comment by TDHofstetter** [comment]
Pretty hard to be sure at this point, but I appear to have M2 and it doesn't support .rbz files. I can't be positive that the copy I just downloaded from OldVersion.com, claiming to be M2, is actually M2; it says that it's 8.0.11752 and it's exactly identical to my extant working install copy. I'll have to dig up another Windows machine (nearly all my machines have migrated to Linux, and SketchUp has never been very happy running under Wine) and try using it to install SketchUp, then verify (a) the version/revision and (b) the .rbz support.

At any rate, it's now moot for my purposes. I've successfully gotten .STL import / export set up and made a note to myself about always including directories found in .rbz files, so I think I'm probably good for the remainder of my life.

Thanks, Thomas. I don't care what your neighbors say, I think you're OK.    8)
